-- Jalankan di Supabase Dashboard > SQL Editor
-- =====================================================================
-- 1) TABEL (sesuai definisi Anda)
-- =====================================================================

create table if not exists public.frame_detection_count_table (
  id                          bigint generated by default as identity not null,
  throwing_detection_count    smallint null default 0,
  smoking_detection_count     integer  null default 0,
  trespassing_detection_count integer  null default 0,
  created_at timestamp without time zone null default (now() AT TIME ZONE 'Asia/Jakarta'::text),
  constraint frame_detection_count_pkey primary key (id)
) tablespace pg_default;

create table if not exists public.frame_detection_uploaded (
  id                bigint generated by default as identity not null,
  created_at        timestamp with time zone not null default (now() AT TIME ZONE 'Asia/Jakarta'::text),
  throwing_frame    text null,
  smoking_frame     text null,
  trespassing_frame text null,
  constraint result_crime_detection_pkey primary key (id)
) tablespace pg_default;

-- Trigger Anda (fungsi insert_frame_detection() harus sudah ada):
-- create trigger trigger_insert_frame_detection
-- after insert on frame_detection_uploaded for each row
-- execute function insert_frame_detection();

-- =====================================================================
-- 2) REALTIME untuk dashboard
-- =====================================================================
alter publication supabase_realtime add table public.frame_detection_count_table;
alter publication supabase_realtime add table public.frame_detection_uploaded;

-- =====================================================================
-- 3) FUNCTION untuk mode ATOMIK (satu hit -> dua tabel, satu transaksi)
--    Dipanggil backend lewat supabase.rpc('insert_frame_detection_bundle', ...)
--    Jika salah satu insert gagal, keduanya di-rollback otomatis.
--    Trigger di frame_detection_uploaded tetap ikut jalan di dalam transaksi.
-- =====================================================================
create or replace function public.insert_frame_detection_bundle(
    p_throwing_count    int  default 0,
    p_smoking_count     int  default 0,
    p_trespassing_count int  default 0,
    p_throwing_frame    text default null,
    p_smoking_frame     text default null,
    p_trespassing_frame text default null
)
returns json
language plpgsql
security definer
as $$
declare
    v_count_id bigint;
    v_frame_id bigint;
begin
    insert into public.frame_detection_count_table (
        throwing_detection_count,
        smoking_detection_count,
        trespassing_detection_count
    ) values (
        p_throwing_count, p_smoking_count, p_trespassing_count
    ) returning id into v_count_id;

    insert into public.frame_detection_uploaded (
        throwing_frame, smoking_frame, trespassing_frame
    ) values (
        p_throwing_frame, p_smoking_frame, p_trespassing_frame
    ) returning id into v_frame_id;

    return json_build_object('count_id', v_count_id, 'frame_id', v_frame_id);
end;
$$;

-- =====================================================================
-- 4) RLS: backend pakai service_role (bypass RLS). Dashboard (anon) baca saja.
-- =====================================================================
alter table public.frame_detection_count_table enable row level security;
alter table public.frame_detection_uploaded    enable row level security;

create policy "dashboard baca count"
    on public.frame_detection_count_table for select to anon, authenticated using (true);

create policy "dashboard baca frame"
    on public.frame_detection_uploaded for select to anon, authenticated using (true);